version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cvhere_development
      POSTGRES_USER: cvhere
      POSTGRES_PASSWORD: cvhere_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cvhere -d cvhere_development"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://cvhere:cvhere_dev_password@postgres:5432/cvhere_development
      JWT_SECRET: dev_jwt_secret_change_in_production
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
    command: npm run dev:backend

volumes:
  postgres_data: